### ISSUE TITLE
Please answer

### ISSUE THREAD

**Issue by dongpu1813** [Human-Charity-Coin/HCC-wallet#1]
ann

**Comment by dongpu1813** [comment]
sudo ./configure
configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!
u18.04

**Comment by Nugetzrul3** [comment]
```apt-get install libssl1.0-dev```

**Comment by CryptoLover705** [comment]
@dongpu1813 please visit the discord channel for more information https://discord.gg/pQTBrZWpwK
